server:
  port: 8091
  servlet:
    context-path: /lyt
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: liyitong
    password: liyitong
    driver-class-name: com.mysql.cj.jdbc.Driver
